In [ ]:
import json
import pandas as pd
import numpy as np
import re
from datetime import datetime
from sklearn.preprocessing import MinMaxScaler, LabelEncoder

In [ ]:
import json
import pandas as pd
import re

def load_robustly(file_path):
    records = []
    malformed_objects_count = 0
    try:
        with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
            content = f.read()

        # Strip outer brackets if it's a single JSON array
        cleaned_content = content.strip()
        if cleaned_content.startswith('[') and cleaned_content.endswith(']') and len(cleaned_content) > 2:
            cleaned_content = cleaned_content[1:-1]

        # Replace '},{' with '}\n{' to get each object on a new line for easier parsing
        object_strings = re.split(r'}\s*,\s*\{', cleaned_content)

        # Reconstruct full object strings with their braces
        parsed_object_strings = []
        if len(object_strings) == 1 and object_strings[0].strip(): # Single object case
            parsed_object_strings.append(object_strings[0].strip())
        elif len(object_strings) > 1: # Multiple objects
            parsed_object_strings.append(object_strings[0].strip() + '}')
            for i in range(1, len(object_strings) - 1):
                parsed_object_strings.append('{' + object_strings[i].strip() + '}')
            parsed_object_strings.append('{' + object_strings[-1].strip())

        for i, obj_str in enumerate(parsed_object_strings):
            obj_str = obj_str.strip()
            if not obj_str:
                continue
            # Ensure the string is wrapped in braces before attempting to parse
            if not obj_str.startswith('{'):
                obj_str = '{' + obj_str
            if not obj_str.endswith('}'):
                obj_str = obj_str + '}'

            try:
                records.append(json.loads(obj_str))
            except json.JSONDecodeError as e:
                malformed_objects_count += 1
                # print(f"Skipped malformed object (index {i}) in {file_path}. Error: {e}. Content start: {obj_str[:100]}...")
            except Exception as e:
                malformed_objects_count += 1
                # print(f"Skipped object (index {i}) due to unexpected error in {file_path}. Error: {e}. Content start: {obj_str[:100]}...")

    except Exception as e:
        print(f"An unexpected error occurred while reading or processing {file_path}: {e}")
        return [] # Return empty list on major file processing errors

    print(f"Successfully loaded {len(records)} records from {file_path}.")
    print(f"Skipped {malformed_objects_count} malformed objects from {file_path}.")
    return records

cleaned_data = load_robustly(
    "/content/drive/MyDrive/Infosys_Datasets/cleaned_enron_emails.json"
)
threaded_data = load_robustly(
    "/content/drive/MyDrive/Infosys_Datasets/threaded_emails.json"
)

cleaned_df = pd.DataFrame(cleaned_data)
threaded_df = pd.DataFrame(threaded_data)

print(f"cleaned_df shape: {cleaned_df.shape}")
print(f"threaded_df shape: {threaded_df.shape}")

Successfully loaded 482552 records from /content/drive/MyDrive/Infosys_Datasets/cleaned_enron_emails.json.
Skipped 8 malformed objects from /content/drive/MyDrive/Infosys_Datasets/cleaned_enron_emails.json.
Successfully loaded 22974 records from /content/drive/MyDrive/Infosys_Datasets/threaded_emails.json.
Skipped 26444 malformed objects from /content/drive/MyDrive/Infosys_Datasets/threaded_emails.json.
cleaned_df shape: (482552, 7)
threaded_df shape: (22974, 11)

In [ ]:
cleaned_df.head()
threaded_df.head()

,MessageID,From,To,InReplyTo,Subject,Date,Body,ThreadKey,Filename,ThreadID,ThreadPosition
0,<23987417.1075857585124.JavaMail.evans@thyme>,slafontaine@globalp.com,john.arnold@enron.com,,re:summer inverses,"Thu, 07 Dec 2000 01:27:00 -0800",they are crazy but mite have to scale in which...,"summer inverses::Thu, 07 Dec 2000 01:27:00 -0800",23.,thread-218b74fb-b061-43b7-a3a0-3935a88ec145,3
1,<19171686.1075857585034.JavaMail.evans@thyme>,slafontaine@globalp.com,john.arnold@enron.com,,re:summer inverses,"Fri, 08 Dec 2000 05:05:00 -0800",i suck-hope youve made more money in natgas la...,"summer inverses::Fri, 08 Dec 2000 05:05:00 -0800",19.,thread-218b74fb-b061-43b7-a3a0-3935a88ec145,6
2,<3552781.1075857584209.JavaMail.evans@thyme>,john.arnold@enron.com,slafontaine@globalp.com,,re:summer inverses,"Mon, 11 Dec 2000 08:51:00 -0800",amazing how with cash futures at $1 and the ba...,"summer inverses::Mon, 11 Dec 2000 08:51:00 -0800",187.,thread-218b74fb-b061-43b7-a3a0-3935a88ec145,9
3,<30245340.1075852710341.JavaMail.evans@thyme>,john.arnold@enron.com,steve.lafontaine@bankofamerica.com,,Re:,"Sun, 13 May 2001 20:33:00 -0700",most bullish thing at this point is moving clo...,"::Sun, 13 May 2001 20:33:00 -0700",4.,thread-7073203c-410c-43da-a3bc-551e58f31f9f,3
4,<1864054.1075857631234.JavaMail.evans@thyme>,steve.lafontaine@bankofamerica.com,john.arnold@enron.com,,RE:,"Mon, 14 May 2001 00:51:00 -0700",i think thats rite -think curve flattens somew...,"::Mon, 14 May 2001 00:51:00 -0700",69.,thread-7073203c-410c-43da-a3bc-551e58f31f9f,4

In [ ]:
!sed -n '971300,971330p' /content/drive/MyDrive/Infosys_Datasets/cleaned_enron_emails.json

  {
    "From": "twanda.sweet@enron.com",
    "To": "aleck.dadson@enron.com",
    "Subject": "Project Stanley",
    "Date": "Mon, 12 Jun 2000 10:50:00 -0700",
    "Body": "Mr. Dadson, please be advised that a conference call regarding the\nabove-referenced matter has been scheduled for this Thursday at 9:00am\ncentral standard time.  The participants are as follows:\n\nRichard Sanders\nRob Hemstock (Calgary)\nRick Shapiro\nAl Dadson\n\nPlease let me know if this time is not convenient for you.  Also, please\nprovide me with a phone number.  The number that we currently have in the\nEnron directory is not a working number (416-214-1740).\n\nThanks\nTwanda\n713-853-9402",
    "ThreadKey": "project stanley::Mon, 12 Jun 2000 10:50:00 -0700",
    "Filename": "175."
  },
  {
    "From": "richard.sanders@enron.com",
    "To": "robert.williams@enron.com",
    "Subject": "Re: FW: Strategy & End Game for FERC Proceeding",
    "Date": "Mon, 08 Jan 2001 02:32:00 -0800",
    "Body": "This is an ENA issue.\n\n\n\nRobert C Williams@ENRON_DEVELOPMENT\n01/08/2001 08:31 AM\n\nTo: Richard Sanders\ncc:\nSubject: Re: FW: Strategy & End Game for FERC Proceeding\n\nRichard?\n---------------------- Forwarded by Robert C Williams/ENRON_DEVELOPMENT on\n01/08/2001 08:38 AM ---------------------------\n\n\nVicki Sharp@EES\n01/07/2001 12:15 PM\nTo: Robert C Williams/ENRON_DEVELOPMENT@ENRON_DEVELOPMENT\ncc:\n\nSubject: Re: FW: Strategy & End Game for FERC Proceeding\n\nCan you confirm with Richard Sanders that this is an ENA issue?\n\n\n\nRobert C Williams@ENRON_DEVELOPMENT\n01/05/2001 12:36 PM\nTo: Vicki Sharp@ENRON_DEVELOPMENT\ncc:\nSubject: FW: Strategy & End Game for FERC Proceeding\n\nfyi\n---------------------- Forwarded by Robert C Williams/ENRON_DEVELOPMENT on\n01/05/2001 12:42 PM ---------------------------\n\n\n\"Fergus, Gary S.\" <GFergus@brobeck.com> on 01/05/2001 11:38:28 AM\nTo: \"Andy Pickens (E-mail)\" <apickens@gibbs-bruns.com>, \"Conner, Randall\"\n<RConner@brobeck.com>, \"David J. Noonan (E-mail)\" <djn@pkns.com>, \"Jean\nFrizzell (E-mail)\" <jfrizzell@gibbs-bruns.com>, \"Meringolo, Peter\"\n<PMeringolo@brobeck.com>, \"Michael L. Kirby (E-mail)\" <dcastro@pkns.com>,\n\"Mike D. Smith (E-mail)\" <msmith1@enron.com>, \"Molland, Michael\"\n<MMolland@brobeck.com>, \"Richard B. Sanders Esq. (E-mail)\"\n<richard.b.sanders@enron.com>, \"Robert C. Williams (E-mail)\"\n<Robert.C.Williams@enron.com>, \"Susan Bisop (E-mail)\"\n<sbishop@gibbs-bruns.com>\ncc:\n\nSubject: FW: Strategy & End Game for FERC Proceeding\n\n\nFYI\nThanks\nGary\n\n-----Original Message-----\nFrom: Jeffrey Watkiss [mailto:dwatkiss@bracepatt.com]\nSent: Friday, January 05, 2001 9:24 AM\nTo: gfergus@brobeck.com; rsander@enron.com; sbishop@gibbs-bruns.com\nCc: jsteffe@enron.com; rshapiro@enron.com; smara@enron.com\nSubject: Strategy & End Game for FERC Proceeding\n\n\nAs you are aware, FERC's chief ALJ is presiding over administrative\nproceedings, ordered by FERC, that ostensibly are intended to provide the\nCal. utilities with reasonable forward power supply contracts, but, in fact,\nare being used equally to force sellers to the ISO and PX during the 3d and\n4th Q 2000 to refund some of their profits from those sales.  The refund\nwill take the form of deeply discounted forward sales commitments to the\nutilities.  The impetus for marketers or independent generators to play ball\nis the threat that FERC may revoke their authorization to make power\nwholesales at market-based as opposed to regulated cost-based rates or take\nsome other punitive step.\n\nMy concern is that this is a terribly one-sided negotiation.  Marketers and\ngenerators are being asked to put their profits on the table - profits that\nFERC's general counsel's office and FERC itself have concluded they have no\npower to touch - and proceed to negotiate against themselves.\n\nEnron has good people representing them in these FERC proceedings - Sue\nMara, Donna Fulton, Sarah Novosel and, when needed, my colleague Ron\nCarroll.  What I am concerned about is that they do not have a concrete\nstrategy or end game to pursue.  Among other things, Enron 's strategy\nshould include requiring the utilities, FERC  and the CPUC to put some value\non the table together with the marketers' and generators' profits.  As these\nvalues may implicate strategy in the California civil actions, I thought I\nshould run my thioughts by you.\n\nSpecifically, I think Enron (and its allies) should insist that as\nprecondition of even considering discounted forward sales:\n\n1.  FERC and the CPUC must commit to file in the District Ct. action\npleadings in support of a motion ito dismiss the complaints on the ground of\nexclusive FERC jurisdiciton.\n\n2.  FERC agree to vacate on rehearing as unsupported by substantial evidence\nits December 15 finding that rates had been unjust and unreasonable.\n\n3.  The utilities and CPUC commit to auctioning off all or some large\npercentage of the utilities' retail customer base.\n\nThere may be other quid pro quo considerations.  I think it is imperative\nthat Enron decide now what they should be.   Politically (and quite likely\ncommercially) it is not an option for Enron to pull out of the FERC\nproceedings.  Therefore, we need to start changing what is at stake in the\nFERC proceeding and directing it toward our end game.\n\nPlease let me know if you wish to discuss this further.\n\n\n=======================================================\nThis email message is for the sole use of the intended recipient(s) and may\ncontain confidential and privileged information. Any unauthorized review,\nuse, disclosure or distribution is prohibited. If you are not the intended\nrecipient, please contact the sender by reply email and destroy all copies of\nthe original message.\n\nTo reply to our email administrator directly, send an email to\npostmaster@brobeck.com\nBROBECK PHLEGER & HARRISON LLP\nhttp://www.brobeck.com",
    "ThreadKey": "strategy & end game for ferc proceeding::Mon, 08 Jan 2001 02:32:00 -0800",
    "Filename": "1245."
  },
  {
    "From": "showard@agsk.com",
    "To": "brian.barth@enron.com",
    "Subject": "Expert Witness for ECT/Questions For You",
    "Date": "Wed, 28 Mar 2001 00:44:00 -0800",
    "Body": "We have recently engaged an investment banker to testify as an expert for ECT\nabout the quality of our due diligence in the NSM transaction.  (This is\nstandard procedure in a litigation matter of this type.)  Our \"expert\" has now\nread all four volumes of your deposition, and I have sent him a slightly\nedited version of your due diligence notes.  However, our expert still needs\nto conduct more \"due diligence\" of his own, including talking or meeting\n(probably separately) with you and Kevin and possibly Tom Glanville.  I will\ncall you shortly to schedule a conference call or a meeting.  You and I will\ntalk separately before any such call or meeting takes place.\n\nIn the meantime, I would appreciate it if you could provide me with answers to\nthe following questions: 1.  Please send me your personal resume, with an eye\ntoward showing your\nexperience and qualifications to conduct due diligence.\n\n2.  Are you aware of any internal check-lists, document review requests or\nlists, agendas (overall, meeting- or conference call-related, or otherwise)\nand any other documents which would show matters reviewed or to-be reviewed in\nconnection with the NSM transaction?  (We will separately review the Enron\ndocuments that have been produced in the litigation to see if we can identify\nany such materials ourselves.)\n\n3.  Was any due diligence done on NTS?\n\nThanks, Brian.  I will work hard to minimize the time you have to spend in\nthis phase of our endeavor.  It will be nothing close to the time that you\nspent on your deposition and preparation\n\nSteve Howard\nAlschuler Grossman Stein & Kahan LLP\nphone: 310-407-7613\nfax: 310-552-6077\ne-mail:  showard@agsk.com\n\n\n\n\n\n\n\n\n\n\n\n\n................................................\n\nALSCHULER GROSSMAN STEIN & KAHAN LLP\nATTORNEYS AT LAW\nwww.agsk.com\n\n2049 Century Park East\nThirty-Ninth Floor\nLos Angeles, CA 90067-3213\nTel 310-277-1226\nFax 310-552-6077\n\nThis transmission is intended only for the use\nof the addressee and may contain information\nthat is privileged, confidential and exempt from\ndisclosure under applicable law. If you are not\nthe intended recipient, or the employee or agent\nresponsible for delivering the message to the\nintended recipient, you are hereby notified that\nany dissemination, distribution or copying of\nthis communication is strictly prohibited.\n\nIf you have received this communication\nin error, please notify us immediately\nvia e-mail at postmaster@agsk.com or\nby telephone at 310-277-1226. Thank you.\n\n...............................................",
    "ThreadKey": "expert witness for ect/questions for you::Wed, 28 Mar 2001 00:44:00 -0800",
    "Filename": "1731."
  },
  {
    "From": "richard.sanders@enron.com",
    "To": "drank@bracepat.com",
    "Subject": "Returned mail: Host unknown (Name server: brcepat.com: host not found)",

In [ ]:
import json
import pandas as pd

def load_json_safely(file_path):
    records = []
    bad_lines = 0

    with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
        for i, line in enumerate(f, start=1):
            try:
                records.append(json.loads(line))
            except json.JSONDecodeError:
                bad_lines += 1

    print(f"Loaded records: {len(records)}")
    print(f"Skipped corrupted lines: {bad_lines}")
    return records

cleaned_data = load_json_safely(
    "/content/drive/MyDrive/Infosys_Datasets/cleaned_enron_emails.json"
)

threaded_data = load_json_safely(
    "/content/drive/MyDrive/Infosys_Datasets/threaded_emails.json"
)

cleaned_df = pd.DataFrame(cleaned_data)
threaded_df = pd.DataFrame(threaded_data)

Loaded records: 0
Skipped corrupted lines: 4343002
Loaded records: 0
Skipped corrupted lines: 3444622

In [ ]:
import pandas as pd
import json

try:
    cleaned_df = pd.read_json(
        "/content/drive/MyDrive/Infosys_Datasets/cleaned_enron_emails.json",
        encoding="utf-8",
        encoding_errors="ignore"
    )
except (ValueError, json.JSONDecodeError) as e:
    print(f"Error loading cleaned_enron_emails.json: {e}")
    cleaned_df = pd.DataFrame() # Initialize as empty DataFrame on error

try:
    threaded_df = pd.read_json(
        "/content/drive/MyDrive/Infosys_Datasets/threaded_emails.json",
        encoding="utf-8",
        encoding_errors="ignore"
    )
except (ValueError, json.JSONDecodeError) as e:
    print(f"Error loading threaded_emails.json: {e}")
    threaded_df = pd.DataFrame() # Initialize as empty DataFrame on error

print(cleaned_df.shape)
print(threaded_df.shape)

Error loading cleaned_enron_emails.json: Unmatched ''"' when when decoding 'string'
Error loading threaded_emails.json: Unmatched ''"' when when decoding 'string'
(0, 0)
(0, 0)

In [ ]:
!head -n 5 /content/drive/MyDrive/Infosys_Datasets/cleaned_enron_emails.json

[
  {
    "From": "",
    "To": "",
    "Subject": "",

In [ ]:
import re
import json
import pandas as pd

file_path = "/content/drive/MyDrive/Infosys_Datasets/cleaned_enron_emails.json"

with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
    raw_text = f.read()

print("Raw file loaded")
print("Total characters:", len(raw_text))

Raw file loaded
Total characters: 1048576000

In [ ]:
pattern = re.compile(r"\{.*?\}", re.DOTALL)

matches = pattern.findall(raw_text)

print("Potential records found:", len(matches))

Potential records found: 486174

In [ ]:
records = []
failed = 0

for obj in matches:
    try:
        # Fix common quote issues
        fixed = obj.replace('\n', ' ').replace('\r', ' ')
        records.append(json.loads(fixed))
    except json.JSONDecodeError:
        failed += 1

print("Recovered records:", len(records))
print("Failed records:", failed)

Recovered records: 481197
Failed records: 4977

In [ ]:
cleaned_df = pd.DataFrame(records)

print("Final DataFrame Shape:", cleaned_df.shape)
cleaned_df.head()

Final DataFrame Shape: (481197, 7)

,From,To,Subject,Date,Body,ThreadKey,Filename
0,,,,,,::,.DS_Store
1,,,,,,::,.DS_Store
2,msagel@home.com,jarnold@enron.com,Status,"Thu, 16 Nov 2000 09:30:00 -0800",John:\n?\nI'm not really sure what happened be...,"status::Thu, 16 Nov 2000 09:30:00 -0800",36.
3,slafontaine@globalp.com,john.arnold@enron.com,re:summer inverses,"Fri, 08 Dec 2000 05:05:00 -0800",i suck-hope youve made more money in natgas la...,"summer inverses::Fri, 08 Dec 2000 05:05:00 -0800",19.
4,iceoperations@intcx.com,"icehelpdesk@intcx.com, internalmarketing@intcx...",The WTI Bullet swap contracts,"Tue, 15 May 2001 09:43:00 -0700","Hi,\n\n\nFollowing the e-mail you have receive...","the wti bullet swap contracts::Tue, 15 May 200...",50.

In [ ]:
file_path = "/content/drive/MyDrive/Infosys_Datasets/threaded_emails.json"

with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
    raw_text = f.read()

matches = re.findall(r"\{.*?\}", raw_text, re.DOTALL)

records = []
failed = 0

for obj in matches:
    try:
        fixed = obj.replace('\n', ' ').replace('\r', ' ')
        records.append(json.loads(fixed))
    except json.JSONDecodeError:
        failed += 1

threaded_df = pd.DataFrame(records)

print("Threaded DF Shape:", threaded_df.shape)
print("Failed records:", failed)
threaded_df.head()

Threaded DF Shape: (235324, 11)
Failed records: 4268

,MessageID,From,To,InReplyTo,Subject,Date,Body,ThreadKey,Filename,ThreadID,ThreadPosition
0,<17938862.1075857585990.JavaMail.evans@thyme>,john.arnold@enron.com,slafontaine@globalp.com,,re:summer inverses,"Wed, 06 Dec 2000 21:38:00 -0800",seems crazy. if you're willing to ride it for...,"summer inverses::Wed, 06 Dec 2000 21:38:00 -0800",18.,thread-218b74fb-b061-43b7-a3a0-3935a88ec145,0.0
1,<23987417.1075857585124.JavaMail.evans@thyme>,slafontaine@globalp.com,john.arnold@enron.com,,re:summer inverses,"Thu, 07 Dec 2000 01:27:00 -0800",they are crazy but mite have to scale in which...,"summer inverses::Thu, 07 Dec 2000 01:27:00 -0800",23.,thread-218b74fb-b061-43b7-a3a0-3935a88ec145,3.0
2,<19171686.1075857585034.JavaMail.evans@thyme>,slafontaine@globalp.com,john.arnold@enron.com,,re:summer inverses,"Fri, 08 Dec 2000 05:05:00 -0800",i suck-hope youve made more money in natgas la...,"summer inverses::Fri, 08 Dec 2000 05:05:00 -0800",19.,thread-218b74fb-b061-43b7-a3a0-3935a88ec145,6.0
3,<3552781.1075857584209.JavaMail.evans@thyme>,john.arnold@enron.com,slafontaine@globalp.com,,re:summer inverses,"Mon, 11 Dec 2000 08:51:00 -0800",amazing how with cash futures at $1 and the ba...,"summer inverses::Mon, 11 Dec 2000 08:51:00 -0800",187.,thread-218b74fb-b061-43b7-a3a0-3935a88ec145,9.0
4,<16522398.1075857584074.JavaMail.evans@thyme>,john.arnold@enron.com,slafontaine@globalp.com,,re:summer inverses,"Mon, 11 Dec 2000 09:04:00 -0800",a couple more thoughts. certainly losing lots...,"summer inverses::Mon, 11 Dec 2000 09:04:00 -0800",181.,thread-218b74fb-b061-43b7-a3a0-3935a88ec145,13.0

In [ ]:
cleaned_df.head()
threaded_df.head()

,MessageID,From,To,InReplyTo,Subject,Date,Body,ThreadKey,Filename,ThreadID,ThreadPosition
0,<17938862.1075857585990.JavaMail.evans@thyme>,john.arnold@enron.com,slafontaine@globalp.com,,re:summer inverses,"Wed, 06 Dec 2000 21:38:00 -0800",seems crazy. if you're willing to ride it for...,"summer inverses::Wed, 06 Dec 2000 21:38:00 -0800",18.,thread-218b74fb-b061-43b7-a3a0-3935a88ec145,0.0
1,<23987417.1075857585124.JavaMail.evans@thyme>,slafontaine@globalp.com,john.arnold@enron.com,,re:summer inverses,"Thu, 07 Dec 2000 01:27:00 -0800",they are crazy but mite have to scale in which...,"summer inverses::Thu, 07 Dec 2000 01:27:00 -0800",23.,thread-218b74fb-b061-43b7-a3a0-3935a88ec145,3.0
2,<19171686.1075857585034.JavaMail.evans@thyme>,slafontaine@globalp.com,john.arnold@enron.com,,re:summer inverses,"Fri, 08 Dec 2000 05:05:00 -0800",i suck-hope youve made more money in natgas la...,"summer inverses::Fri, 08 Dec 2000 05:05:00 -0800",19.,thread-218b74fb-b061-43b7-a3a0-3935a88ec145,6.0
3,<3552781.1075857584209.JavaMail.evans@thyme>,john.arnold@enron.com,slafontaine@globalp.com,,re:summer inverses,"Mon, 11 Dec 2000 08:51:00 -0800",amazing how with cash futures at $1 and the ba...,"summer inverses::Mon, 11 Dec 2000 08:51:00 -0800",187.,thread-218b74fb-b061-43b7-a3a0-3935a88ec145,9.0
4,<16522398.1075857584074.JavaMail.evans@thyme>,john.arnold@enron.com,slafontaine@globalp.com,,re:summer inverses,"Mon, 11 Dec 2000 09:04:00 -0800",a couple more thoughts. certainly losing lots...,"summer inverses::Mon, 11 Dec 2000 09:04:00 -0800",181.,thread-218b74fb-b061-43b7-a3a0-3935a88ec145,13.0

In [ ]:
#1️⃣ DATA CLEANING

In [ ]:
#Handling Missing Values

cleaned_df.isnull().sum()

From         6
To           6
Subject      6
Date         6
Body         6
ThreadKey    6
Filename     6
dtype: int64

In [ ]:
cleaned_df = cleaned_df.dropna(subset=['Body'])

In [ ]:
cleaned_df.isnull().sum()

From         0
To           0
Subject      0
Date         0
Body         0
ThreadKey    0
Filename     0
dtype: int64

In [ ]:
#Removing Duplicate Records

before = len(cleaned_df)
cleaned_df = cleaned_df.drop_duplicates(subset=['Body']).copy() # Added .copy() to prevent SettingWithCopyWarning
after = len(cleaned_df)

print("Duplicates removed:", before - after)

Duplicates removed: 249128

In [ ]:
#Correct Invalid / Inconsistent Values

cleaned_df['Subject'] = cleaned_df['Subject'].fillna("NO_SUBJECT")

In [ ]:
cleaned_df[['Subject']].head()

                                             Subject
0
2                                             Status
3                                 re:summer inverses
4                      The WTI Bullet swap contracts
5  Invitation: EBS/GSS Meeting w/Bristol Babcock ...

from matplotlib import pyplot as plt
_df_0['index'].plot(kind='hist', bins=20, title='index')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_1.groupby('Subject').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

<string>:18: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['index']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'index'}, axis=1)
              .sort_values('index', ascending=True))
  xs = counted['index']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_2.sort_values('index', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Subject')):
  _plot_series(series, series_name, i)
  fig.legend(title='Subject', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_3['index'].plot(kind='line', figsize=(8, 4), title='index')
plt.gca().spines[['top', 'right']].set_visible(False)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_4['Subject'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_4, x='index', y='Subject', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [ ]:
#Fixing Formatting Errors

cleaned_df['Erom'] = cleaned_df['From'].str.lower().str.strip()
cleaned_df['To'] = cleaned_df['To'].str.lower().str.strip()

In [ ]:
cleaned_df[['From', 'To']].head()

,From,To
0,,
2,msagel@home.com,jarnold@enron.com
3,slafontaine@globalp.com,john.arnold@enron.com
4,iceoperations@intcx.com,"icehelpdesk@intcx.com, internalmarketing@intcx..."
5,jeff.youngflesh@enron.com,"anthony.gilmore@enron.com, colleen.koenig@enro..."

In [ ]:
#2️⃣ DATA VALIDATION

In [ ]:
#Schema Validation

expected_columns = ['From', 'To', 'Subject', 'Body', 'Date']
missing_cols = set(expected_columns) - set(cleaned_df.columns)

print("Missing columns:", missing_cols)

Missing columns: set()

In [ ]:
#Mandatory Field Checks

mandatory_check = cleaned_df[['From', 'To', 'Body']].isnull().sum()
mandatory_check

From    0
To      0
Body    0
dtype: int64

In [ ]:
#Range / Logical Checks

invalid_dates = cleaned_df['Date'].isnull().sum()
print("Invalid Dates:", invalid_dates)

Invalid Dates: 0

In [ ]:
#Referential Integrity (Threads)

threaded_df[['ThreadID']].head()

                                      ThreadID
0  thread-218b74fb-b061-43b7-a3a0-3935a88ec145
1  thread-218b74fb-b061-43b7-a3a0-3935a88ec145
2  thread-218b74fb-b061-43b7-a3a0-3935a88ec145
3  thread-218b74fb-b061-43b7-a3a0-3935a88ec145
4  thread-218b74fb-b061-43b7-a3a0-3935a88ec145

In [ ]:
#3️⃣ DATA TRANSFORMATION

In [ ]:
#Data Type Conversion

cleaned_df['Date'] = pd.to_datetime(cleaned_df['Date'], errors='coerce', utc=True)

In [ ]:
cleaned_df.dtypes

From                      object
To                        object
Subject                   object
Date         datetime64[ns, UTC]
Body                      object
ThreadKey                 object
Filename                  object
Erom                      object
dtype: object

In [ ]:
#Unit Conversion (Timezone → UTC)

cleaned_df['Date_utc'] = cleaned_df['Date'].dt.tz_convert('UTC')
cleaned_df[['Date_utc']].head()

                   Date_utc
0                       NaT
2 2000-11-16 17:30:00+00:00
3 2000-12-08 13:05:00+00:00
4 2001-05-15 16:43:00+00:00
5 2000-11-27 09:49:00+00:00

In [ ]:
#Normalization

cleaned_df['email_length'] = cleaned_df['Body'].apply(len)

scaler = MinMaxScaler()
cleaned_df['email_length_norm'] = scaler.fit_transform(
    cleaned_df[['email_length']]
)

cleaned_df[['email_length', 'email_length_norm']].head()

   email_length  email_length_norm
0             0           0.000000
2           600           0.000298
3           275           0.000137
4          1066           0.000530
5           198           0.000098

In [ ]:
#Aggregation (Daily → Monthly)

cleaned_df['month'] = cleaned_df['Date_utc'].dt.to_period('M')

monthly_counts = cleaned_df.groupby('month').size().reset_index(name='email_count')
monthly_counts.head()

/tmp/ipython-input-939154425.py:3: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  cleaned_df['month'] = cleaned_df['Date_utc'].dt.to_period('M')

     month  email_count
0  1980-01          273
1  1986-04            1
2  1986-05            1
3  1997-01            1
4  1997-03           10

In [ ]:
#Encoding (Categorical → Numeric)

encoder = LabelEncoder()
cleaned_df['sender_id'] = encoder.fit_transform(cleaned_df['From'])

cleaned_df[['From', 'sender_id']].head()

                        From  sender_id
0                                     0
2            msagel@home.com      11714
3    slafontaine@globalp.com      15187
4    iceoperations@intcx.com       6795
5  jeff.youngflesh@enron.com       7576

In [ ]:
#4️⃣ DATA FILTERING

In [ ]:
#1 Remove Unnecessary Columns

filtered_df = cleaned_df[['From', 'To', 'Subject', 'Body', 'Date_utc']].copy()
filtered_df.head()

,From,To,Subject,Body,Date_utc
0,,,,,NaT
2,msagel@home.com,jarnold@enron.com,Status,John:\n?\nI'm not really sure what happened be...,2000-11-16 17:30:00+00:00
3,slafontaine@globalp.com,john.arnold@enron.com,re:summer inverses,i suck-hope youve made more money in natgas la...,2000-12-08 13:05:00+00:00
4,iceoperations@intcx.com,"icehelpdesk@intcx.com, internalmarketing@intcx...",The WTI Bullet swap contracts,"Hi,\n\n\nFollowing the e-mail you have receive...",2001-05-15 16:43:00+00:00
5,jeff.youngflesh@enron.com,"anthony.gilmore@enron.com, colleen.koenig@enro...",Invitation: EBS/GSS Meeting w/Bristol Babcock ...,Conference Room TBD.\n\nThis meeting will be t...,2000-11-27 09:49:00+00:00

In [ ]:
#2 Drop Incomplete Records

filtered_df = filtered_df.dropna()
filtered_df.shape

(232061, 5)

In [ ]:
#5️⃣ DATA ENRICHMENT

In [ ]:
#1 Derived Fields

filtered_df['word_count'] = filtered_df['Body'].apply(lambda x: len(x.split()))
filtered_df[['word_count']].head()

   word_count
2         104
3          51
4         170
5          29
6         137

In [ ]:
#2 Domain Extraction (Enrichment)

filtered_df['sender_domain'] = filtered_df['From'].apply(lambda x: x.split('@')[-1])
filtered_df[['From', 'sender_domain']].head()

                        From sender_domain
2            msagel@home.com      home.com
3    slafontaine@globalp.com   globalp.com
4    iceoperations@intcx.com     intcx.com
5  jeff.youngflesh@enron.com     enron.com
6  caroline.abramo@enron.com     enron.com

In [ ]:
#6️⃣ DATA DEDUPLICATION

In [ ]:
#1 Exact Match Deduplication

before = len(filtered_df)
filtered_df = filtered_df.drop_duplicates()
after = len(filtered_df)

print("Deduplicated:", before - after)

Deduplicated: 0

In [ ]:
#2 Primary-Key Deduplication

filtered_df = filtered_df.drop_duplicates(subset=['From', 'Date_utc'])
filtered_df.head()

,From,To,Subject,Body,Date_utc,word_count,sender_domain
2,msagel@home.com,jarnold@enron.com,Status,John:\n?\nI'm not really sure what happened be...,2000-11-16 17:30:00+00:00,104,home.com
3,slafontaine@globalp.com,john.arnold@enron.com,re:summer inverses,i suck-hope youve made more money in natgas la...,2000-12-08 13:05:00+00:00,51,globalp.com
4,iceoperations@intcx.com,"icehelpdesk@intcx.com, internalmarketing@intcx...",The WTI Bullet swap contracts,"Hi,\n\n\nFollowing the e-mail you have receive...",2001-05-15 16:43:00+00:00,170,intcx.com
5,jeff.youngflesh@enron.com,"anthony.gilmore@enron.com, colleen.koenig@enro...",Invitation: EBS/GSS Meeting w/Bristol Babcock ...,Conference Room TBD.\n\nThis meeting will be t...,2000-11-27 09:49:00+00:00,29,enron.com
6,caroline.abramo@enron.com,mike.grigsby@enron.com,Harvard Mgmt,Mike- I have their trader coming into the offi...,2000-12-12 17:33:00+00:00,137,enron.com

In [ ]:
#7️⃣ DATA MASKING & SECURITY

In [ ]:
#1 Mask Email Addresses

def mask_email(email):
    return email[:2] + "****@" + email.split('@')[-1]

filtered_df['from_masked'] = filtered_df['From'].apply(mask_email)
filtered_df[['From', 'from_masked']].head()

                        From         from_masked
2            msagel@home.com     ms****@home.com
3    slafontaine@globalp.com  sl****@globalp.com
4    iceoperations@intcx.com    ic****@intcx.com
5  jeff.youngflesh@enron.com    je****@enron.com
6  caroline.abramo@enron.com    ca****@enron.com

In [ ]:
#2 Hashing

import hashlib

filtered_df['from_hash'] = filtered_df['From'].apply(
    lambda x: hashlib.sha256(x.encode()).hexdigest()
)

filtered_df[['from_hash']].head()

                                           from_hash
2  17f17dd4074f3955606b951741ea785f2360278b50488a...
3  b35c238d5a30faf4834ebd80d93a72b8e365795c57493e...
4  b633b679b3fe3255dddd3f6589837bc4a4d7e717f64fd7...
5  4cc1213fff277a44aebb500d15668e0876e7cd698b8008...
6  86f6e878c74072f2726a20be9e94a22f57e51161491701...

In [ ]:
#8️⃣ DATA STANDARDIZATION

In [ ]:
filtered_df.columns = [c.lower().replace(" ", "_") for c in filtered_df.columns]
filtered_df.head()

,from,to,subject,body,date_utc,word_count,sender_domain,from_masked,from_hash
2,msagel@home.com,jarnold@enron.com,Status,John:\n?\nI'm not really sure what happened be...,2000-11-16 17:30:00+00:00,104,home.com,ms****@home.com,17f17dd4074f3955606b951741ea785f2360278b50488a...
3,slafontaine@globalp.com,john.arnold@enron.com,re:summer inverses,i suck-hope youve made more money in natgas la...,2000-12-08 13:05:00+00:00,51,globalp.com,sl****@globalp.com,b35c238d5a30faf4834ebd80d93a72b8e365795c57493e...
4,iceoperations@intcx.com,"icehelpdesk@intcx.com, internalmarketing@intcx...",The WTI Bullet swap contracts,"Hi,\n\n\nFollowing the e-mail you have receive...",2001-05-15 16:43:00+00:00,170,intcx.com,ic****@intcx.com,b633b679b3fe3255dddd3f6589837bc4a4d7e717f64fd7...
5,jeff.youngflesh@enron.com,"anthony.gilmore@enron.com, colleen.koenig@enro...",Invitation: EBS/GSS Meeting w/Bristol Babcock ...,Conference Room TBD.\n\nThis meeting will be t...,2000-11-27 09:49:00+00:00,29,enron.com,je****@enron.com,4cc1213fff277a44aebb500d15668e0876e7cd698b8008...
6,caroline.abramo@enron.com,mike.grigsby@enron.com,Harvard Mgmt,Mike- I have their trader coming into the offi...,2000-12-12 17:33:00+00:00,137,enron.com,ca****@enron.com,86f6e878c74072f2726a20be9e94a22f57e51161491701...

In [ ]:
#9️⃣ ERROR HANDLING & LOGGING

In [ ]:
error_log = []

try:
    pd.to_datetime("invalid-date")
except Exception as e:
    error_log.append(str(e))

error_log

['Unknown datetime string format, unable to parse: invalid-date, at position 0']

In [ ]:
error_log = []

def safe_to_datetime(value, column_name="unknown"):
    try:
        return pd.to_datetime(value)
    except Exception as e:
        error_log.append({
            "column": column_name,
            "value": value,
            "error": str(e)
        })
        return pd.NaT

In [ ]:
#🔟 METADATA HANDLING

In [ ]:
filtered_df['ingestion_time'] = datetime.utcnow()
filtered_df['source_system'] = 'Enron Email Dataset'
filtered_df['data_version'] = 'v1.0'

filtered_df[['ingestion_time', 'source_system', 'data_version']].head()

/tmp/ipython-input-3829850487.py:1: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  filtered_df['ingestion_time'] = datetime.utcnow()

              ingestion_time        source_system data_version
2 2026-01-21 06:40:52.049086  Enron Email Dataset         v1.0
3 2026-01-21 06:40:52.049086  Enron Email Dataset         v1.0
4 2026-01-21 06:40:52.049086  Enron Email Dataset         v1.0
5 2026-01-21 06:40:52.049086  Enron Email Dataset         v1.0
6 2026-01-21 06:40:52.049086  Enron Email Dataset         v1.0

In [ ]:
#1️⃣1️⃣ SAMPLING

In [ ]:
sample_df = filtered_df.sample(n=5, random_state=42)
sample_df

,from,to,subject,body,date_utc,word_count,sender_domain,from_masked,from_hash,ingestion_time,source_system,data_version
159440,jeff.dasovich@enron.com,mday@gmssr.com,Rosenfield exposes phony bankruptcy,----- Forwarded by Jeff Dasovich/NA/Enron on 1...,2000-12-20 12:56:00+00:00,212,enron.com,je****@enron.com,5a37ed79e09fa97afff4b9f6e3126e907a3cf6cddae9dd...,2026-01-21 06:40:52.049086,Enron Email Dataset,v1.0
6302,maggie_timmins@cdnoxy.com,"afowler@arcfinancial.com, alkeo@hotmail.com, a...",WHERE ARE THE BALLOON PRIZES?,"Okay fellow deputies, where are your prizes?\n...",2000-01-13 19:45:00+00:00,223,cdnoxy.com,ma****@cdnoxy.com,24c91fb28058b7df58af14d3af059b033ad3db1f1a6407...,2026-01-21 06:40:52.049086,Enron Email Dataset,v1.0
62330,mike.mcconnell@enron.com,ken.rice@enron.com,Re:,Thanks for the note. Sooners rule. We'll fi...,2001-01-19 07:55:00+00:00,151,enron.com,mi****@enron.com,b61bb4d0bb6d25335d469f9a6efcad0508c9143fc0ae4c...,2026-01-21 06:40:52.049086,Enron Email Dataset,v1.0
398667,mark.haedicke@enron.com,mcunningham@isda.org,Re: Pacific Forest Resources,"At this point, I think they should be a subscr...",2000-03-09 17:52:00+00:00,20,enron.com,ma****@enron.com,04b35390ad540dff884609d0be32537a92bc60f65502e4...,2026-01-21 06:40:52.049086,Enron Email Dataset,v1.0
276591,lisa.bills@enron.com,kay.mann@enron.com,Re: Winston & Strawn Comment: Consents to Assi...,"Kay, I have told Rob that we are not pushing G...",2000-12-10 15:33:00+00:00,368,enron.com,li****@enron.com,03484b6b18b098bb27d694d743863b83d8de8f33b94776...,2026-01-21 06:40:52.049086,Enron Email Dataset,v1.0

In [ ]:
filtered_df.to_csv('final_ingested_enron_emails.csv', index=False)
monthly_counts.to_csv('monthly_email_aggregation.csv', index=False)

In [ ]:
text_col = "final_text"

In [ ]:
!pip install spacy
!python -m spacy download en_core_web_sm

Requirement already satisfied: spacy in /usr/local/lib/python3.12/dist-packages (3.8.11)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /usr/local/lib/python3.12/dist-packages (from spacy) (8.3.10)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.5.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.4.3)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.21.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.32.4)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.12.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.1.4)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.3.3)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim<1.0.0,>=0.3.0->spacy) (8.3.1)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.4.2->spacy) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.4.2->spacy) (7.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy) (3.0.3)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.4.2->spacy) (2.0.1)
Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 43.9 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [ ]:
import spacy
nlp = spacy.load("en_core_web_sm")

def extract_entities(text):
    doc = nlp(text)
    return [(ent.text, ent.label_) for ent in doc.ents]

df["entities"] = df[text_col].apply(extract_entities)

NameError: name 'df' is not defined

In [ ]:
df.head()
df.columns

NameError: name 'df' is not defined

In [ ]:
print("df" in globals())

False

In [ ]:
import pandas as pd

df = pd.read_json("/content/drive/MyDrive/Infosys_Datasets/cleaned_enron_emails.json", lines=True)

ValueError: Expected object or value

In [ ]:
import os
os.path.getsize("/content/drive/MyDrive/Infosys_Datasets/cleaned_enron_emails.json")

1048576000

In [ ]:
{"id":1,"text":"hello"}
{"id":2,"text":"world"}

{'id': 2, 'text': 'world'}

In [ ]:
import pandas as pd
df = pd.read_json("/content/drive/MyDrive/Infosys_Datasets/cleaned_enron_emails.json")

ValueError: Unmatched ''"' when when decoding 'string'

In [ ]:
with open("/content/drive/MyDrive/Infosys_Datasets/cleaned_enron_emails.json", errors="ignore") as f:
    for i in range(10):
        print(f.readline())

[

  {

    "From": "",

    "To": "",

    "Subject": "",

    "Date": "",

    "Body": "",

    "ThreadKey": "::",

    "Filename": ".DS_Store"

  },

In [ ]:
import json

with open("/content/drive/MyDrive/Infosys_Datasets/cleaned_enron_emails.json", errors="ignore") as f:
    raw = f.read()

data = json.loads(raw)

JSONDecodeError: Unterminated string starting at: line 4343002 column 13 (char 1048499281)

In [ ]:
with open("/content/drive/MyDrive/Infosys_Datasets/cleaned_enron_emails.json", errors="ignore") as f:
    for i, line in enumerate(f):
        if i == 4343001:   # zero-based index
            print(line)
            break

    "Body": "Please see the following articles:\n\nSac Bee, Fri, 6/22: Employees: Power supply held down\n\nSac Bee, Fri, 6/22: Consumers cut down their own power in protest\n\nSac Bee, Fri, 6/22: Davis consultants had contract with Edison: The disclos=\nures turn up the heat on the governor for hiring=20\nex-Clinton aides\n\nSD Union, Fri, 6/22: State deal may ease blackout threat\nCanada to supply energy as summer demand rises=20\n\nSD Union, Fri, 6/22: Ex-worker: Duke manipulated market\n\nLA Times, Fri, 6/22: Estimates of power profits disputed\n\nLA Times, Fri, 6/22: Edison plans bond offer at 13% rate\n\nLA Times, Fri, 6/22: Energy company abandons plans for Baldwin Hills plant=\n=20\n\nSF Chron, Fri, 6/22: Western states could feel pinch from California pricin=\ng=20\n\nSF Chron, Fri, 6/22: Feds spurn Duke Energy in its bid to avoid refunds\n\nSF Chron, Fri, 6/22: News Analysis: Davis winning Washington PR battle=20\nPrice cap victory may rob Democrats of campaign issue\n\nSF Chron, Fri, 6/22: Suit filed over report on power lines, health=20\nDeal on transmission grid could raise liability\n\nSF Chron, Fri, 6/22: Texas power firm's shares failing (Enron spotlighted)\nPower baron Enron finds fortunes fading\n\nMercury News, Fri, 6/22: Power firm accused of price-fixing\n\nMercury News, Fri, 6/22: Enron chief: Gov. Davis not to blame for energy cr=\nisis (Jeff Skilling comments, Ken Lay and Enron mentioned)\n\nOC Register, Fri, 6/22: Three say company purposely cut power\nEx-Duke workers say repairs were curbed in order to manipulate market\n\nOC Register, Fri, 6/22: FERC judge tackles task of generating a deal=20\n\nOC Register, Fri, 6/22: Davis seeks $9 billion refund=20\n\nOC Register, Fri, 6/22: Energy notebook: Blackouts are still a hot prospect=\n, officials warn\n\nOC Register, Fri, 6/22: In rolling blackouts, 'together' is all relative\n\n\n\n\n\n\n\n\nEmployees: Power supply held down By Kevin Yamamura and Emily Bazar Bee Cap=\nitol Bureau (Published June 22, 2001)  Three former San Diego Gas & Electri=\nc Co. employees who worked at a Duke Energy plant said Thursday that the ge=\nnerator destroyed working parts, withheld power supply or otherwise took ac=\ntions that they believe drove up the price of electricity.  State officials=\nsaid the whistle-blowers' comments at a state Senate hearing today could p=\nrovide the most damaging illustration yet that power generators held down p=\nroduction to inflate prices on the spot market. Gov. Gray Davis has long al=\nleged that power companies have overcharged the state and utilities.  Jimmy=\nOlkjer, a former assistant control room operator at Duke's South Bay plant=\nin San Diego, said in a phone interview that during the state's power shor=\ntages, Duke cut supply. Although Duke, a Charlotte, N.C.-based company, own=\ned the plant, and it contracted with SDG&E to operate the unit, he said.  \"=\nRather than creating more power, they were creating less,\" Olkjer said. \"I =\nthink there was manipulation of the market.\"  The California Public Utiliti=\nes Commission and several state legislative committees continue to investig=\nate price manipulation allegations, and Attorney General Bill Lockyer has s=\naid he will take witnesses to a grand jury next month.  The generators have=\ndenied they manipulated the market.  \"We stand behind our maintenance prac=\ntices and have done a good job keeping the power flowing,\" Duke spokesman T=\nom Williams told the CBS television network.  But former mechanic Glenn Joh=\nnson said he saw generation units taken \"down for economics.\"  Ed Edwards, =\nalso a mechanic, said he was ordered to destroy 23 pallets of working parts=\n.  \"We were asked, myself and other employees, to disperse of perfectly goo=\nd parts that were used to make repairs of systems and components,\" Edwards =\nsaid.  State Sen. Joe Dunn, D-Santa Ana, chairman of the market-manipulatio=\nn committee, said his staff has been looking for employees or others with i=\nntimate knowledge of power plant operation to come forward, and he promised=\nthat others will testify at future hearings.  \"It's the first time that we=\n've had evidence from directly within power plants in California that the r=\namping up and ramping down of power generation was a response to price and =\nnot to demand,\" Dunn said.  He said he would reach no conclusions until Duk=\ne and other generators testify next month, but he added that the former emp=\nloyees' testimony raises suspicions \"at first blush.\"   The Bee's Kevin Yam=\namura can be reached at (916) 326-5542 or kyamamura@sacbee.com .  =09\n\n\n\n\nConsumers cut their own power in protest  By Silvina Mart?nez Bee S=\ntaff Writer  (Published June 22, 2001)  When the temperature hit 100 degree=\ns at 7 p.m. Thursday, Larry Lynch turned off the air conditioner, unplugged=\nthe refrigerator, pulled out the TV cords and shut down all other applianc=\nes in the house.  Lynch, a 61-year-old newsletter publisher in Sacramento, =\nresponded to the \"Roll Your Own Blackout\" Thursday and joined thousands thr=\noughout the state to protest energy policies and promote conservation by st=\nopping the use of energy from 7-10 p.m.  But the data coming off the grid a=\nt the California Independent System Operator didn't show the effort.  Durin=\ng the first hour of the voluntary shut-off, the demand for energy by PG&E c=\nustomers in Northern California was almost the same as at the same time Wed=\nnesday, ISO officials said.  Protesters didn't expect significant changes o=\nn the grid.  \"I feel it will at least send a message that we don't have to =\ndepend on it (energy),\" said Jackie Bell, 37, a consultant at the Capitol j=\noining the conservation drive from her apartment on Fulton Avenue.  \"It's j=\nust a symbolic act,\" said Peter Lopez of Sacramento, who decided to use the=\nevening to meditate. \"Maybe I'll just go outside, stare at the stars and t=\nry to spot a few constellations in the night.\"  It was the longest day of t=\nhe year, and one of the hottest. But those determined to advocate conservat=\nion didn't mind the sacrifice.  \"People are getting focused on the fact tha=\nt we have power at our end,\" said Joan Blades, a spokeswoman for MoveOn, a =\ngrass-roots organization in the Bay Area and one of hundreds of online grou=\nps passing along the call for the voluntary blackout.  An electrical engine=\ner in Oakland started the \"Roll Your Own Blackout\" idea when he posted a no=\nte in a political chat room in April. Then an artist in Los Angeles forward=\ned the e-mail to a number of friends and from there it quickly spanned the =\nglobe.  By Thursday afternoon, more than 12,000 people had signed up at the=\nMoveOn Web site to join the protest, Blades said.  Many threw blackout par=\nties. In San Francisco, the nonprofit group Global Exchange gathered hundre=\nds around a big bonfire at Ocean Beach.  At his home in east Sacramento, Ly=\nnch did fine without electricity for three hours. He ate tuna salad for din=\nner, watered the lawn and when it got dark, he opened the windows and let s=\nome air in.  \"We should show that people are willing to shut the power off =\nif the prices go too high,\" he said.  ISO has not declared a power emergenc=\ny since May 31.  \"We have seen a consistent conservation on a day-to-day ba=\nsis, and it's making the difference between blackouts and no blackouts,\" IS=\nO spokeswoman Stephanie McCorkle said.  McCorkle encouraged initiatives lik=\ne \"Roll Your Own Blackout.\"  \"People are conserving,\" she said. \"And we can=\nonly support this whole effort.\"   The Bee's Silvina Mart?nez can be reach=\ned at (916) 321-1159 or smartinez@sacbee.com .   =09\n\n\n\n\nDavis consultants had contract with Edison: The disclosures turn up the hea=\nt on the governor for hiring the ex-Clinton aides. By Emily Bazar Bee Capit=\nol Bureau (Published June 22, 2001)  Two consultants hired to advise Gov. G=\nray Davis on energy policy officially disclosed their contract with Souther=\nn California Edison on Thursday, but Davis aides insisted it is not a confl=\nict because \"Edison and the Governor's Office have the same goal.\"  Communi=\ncations consultants Chris Lehane and Mark Fabiani have drawn intense critic=\nism since they were hired last month to shape the Democratic governor's pub=\nlic response to the state energy crisis.  The former Clinton administration=\ncommunication aides -- nicknamed the \"Masters of Disaster\" for their spin =\non the Whitewater, travel office and 1996 fund-raising controversies at the=\nClinton White House -- have come under fire for receiving a six-month, $30=\n,000-a-month contract, more than the governor or anyone on his staff makes.=\nSecretary of State Bill Jones, a Republican who is running for governor n=\next year, has called for an investigation into potential conflicts. State C=\nontroller Kathleen Connell, a Democrat, has said she will not issue paychec=\nks to the pair pending her own investigation.  The criticism mounted after =\nthe duo's economic interest disclosure forms were released late Thursday, s=\nhowing that each has received at least $10,000 under contract from Edison i=\nn the past year.  But Davis spokeswoman Hilary McLean defended their credib=\nility, saying there's no conflict of interest because Lehane and Fabiani bo=\nth disclosed that they had worked for Edison before they signed their contr=\nacts with the state.  Besides, she added, Edison and the governor are worki=\nng toward the same goal: Both want the Legislature to adopt a memorandum of=\nunderstanding, a proposed agreement, that would prevent Edison from going =\nbankrupt by financing a state purchase of the utility's transmission lines.=\n\"It's not a conflict because there's been full disclosure,\" McLean said. =\n\"Edison and the Governor's Office have the same goal, passing the MOU. We'r=\ne working together at this point with Edison.\"  But open-government groups =\nand Republican lawmakers bristled at the notion that disclosure negates any=\npotential conflict.  Derek Cressman of the California Public Interest Rese=\narch Group pointed to a section of state law that prohibits public official=\ns from influencing decisions if it would have \"a material financial effect\"=\non a business entity that provided them $500 or more within the last year.=\n\"You have two individuals on the government payroll who had previously be=\nen on the Edison payroll and it's not clear to whom their loyalties are,\" h=\ne said. \"Just because they've revealed it doesn't mean there's not a confli=\nct there, and that they're not serving two masters.\"  On Thursday, Jones sa=\nid he is awaiting the results of the Fair Political Practices Commission in=\nvestigation and agrees with Connell's decision this week to withhold paymen=\nt from the consultants.  \"This further calls into question the ethics of ho=\nw these individuals were hired and contracts were let,\" Jones said.  Senate=\nRepublican leader Jim Brulte believes there's no question that Lehane and =\nFabiani are violating conflict-of-interest laws and suggested that the two =\nshould be paid out of Davis' campaign funds, which had reached $26 million =\nby Jan. 1.  Brulte, of Rancho Cucamonga, added that he would not vote for a=\nstate budget as long as Lehane and Fabiani remain on the state payroll.  \"=\nThe state of California does not need to be paying political wordsmiths $30=\n,000 a month,\" he said. \"I just wish (Davis) were as frugal with the taxpay=\ners' money as he is with his campaign money.\"   The Bee's Emily Bazar can b=\ne reached at (916) 326-5540 or ebazar@sacbee.com .  =09\n\n\n\n\n\nState deal may ease blackout threat =09\n=09\n\n\n\n\nCanada to supply energy as summer demand rises By Ed Mendel  UNION-TRIBUNE =\nSTAFF WRITER  June 22, 2001  SACRAMENTO -- California may be able to avoid =\nsome of the blackouts predicted for this summer, thanks to a little-known p=\nower-swapping agreement with a Canadian utility.  The arrangement is expect=\ned to give California electricity in July and August from the hydroelectric=\ngenerators of BC Hydro in British Columbia, despite a serious drought in t=\nhe Northwest.  California has sold surplus power in recent months to the go=\nvernment-owned utility, which is expected to return power to the state as h=\neat drives up the demand for electricity.          State deal may ease blac=\nkout threat   Continuing coverage: California's Power Crisis         Despit=\ne the energy crunch, the state often finds itself with surplus power that c=\nan be sold or swapped. For instance, advance power purchases that provide e=\nnergy at a better price may deliver more power than needed at any given tim=\ne, particularly during off-peak hours.  BC Hydro's reservoirs and hydroelec=\ntric generators are a little like an electricity storage battery. By import=\ning California power, BC Hydro has been able to conserve water that can be =\nreleased this summer to produce power for California.  As a result of the a=\ngreement and other factors, state power buyers say they are in a stronger p=\nosition going into the hot summer months than they had expected. So far thi=\ns week, the state has managed to get through a heat wave without so much as=\na Stage 1 power alert.  \"We are in much better shape at this point than I =\nimagined we would have been as little as a month ago,\" said Ray Hart, head =\nof the power purchasing unit in the state Department of Water Resources.  T=\nhe North American Electric Reliability Council, which last month predicted =\n260 hours of rolling blackouts for California this summer, has noticed a ch=\nange in recent weeks.  \"We don't seem to have the crisis we were all expect=\ning,\" said Ellen Vancko, a council spokeswoman. \"But whether that is a shor=\nt-term or a long-term event we don't think anyone knows yet.\"  Much of the =\ncredit for avoiding blackouts is given to unexpectedly high conservation by=\nCalifornians and an increased supply of power. Many generators that had be=\nen shut down for maintenance or lack of payment are now back on line.  But =\nthe hydroelectric power agreement had gone unnoticed until now.  Hart menti=\noned it during a Senate Energy Committee hearing this week. But he declined=\nto reveal the amount of power banked with BC Hydro, saying it could hurt t=\nhe state's competitive position in the market.  \"If I start talking specifi=\ncs,\" said Hart, \"then I have to give out what I am doing every single day, =\nand I have no market position.\"  In the past, California routinely sent pow=\ner to a number of utilities in the Pacific Northwest during the winter when=\nresidents there needed heat. Northwest utilities returned power to Califor=\nnia in the summer when air conditioning drove up demand.  Little was expect=\ned from the reciprocal arrangement this year because California was short o=\nf power last winter as electricity prices soared, and drought has sharply l=\nowered reservoirs in the Northwest. But the agreement with BC Hydro will pr=\novide at least some power this summer.  The state was forced to begin buyin=\ng power in January after its two largest utilities, Southern California Edi=\nson and Pacific Gas and Electric, were unable to borrow because of a $13 bi=\nllion debt. The rates that the utilities could charge their customers were =\nfrozen under a failed deregulation plan as the cost of power on the wholesa=\nle market skyrocketed.  Hart said it took time to convince BC Hydro, which =\nhas demanded cash for some electricity, that it could safely do business wi=\nth California despite big debts owed to generators for power they supplied =\nto the utilities.  \"We have only been able to do it for the last couple of =\nmonths,\" said Hart. \"It took a long time to get them to do it because of cr=\nedit issues.\"  A spokesman for BC Hydro said the utility engages in power s=\nwaps but does not release the name of the other parties or the terms of the=\nagreements.  \"Our first priority is taking care of our own,\" said Warren C=\nousins of BC Hydro. \"We are still looking for opportunities to help out oth=\ner entities when we can.\"  Hart said the state has another arrangement with=\nthe federal Bonneville Power Authority, but again refused to provide detai=\nls. He said the state has sold surplus power to several buyers, including t=\nhe Los Angeles Department of Water and Power.  Information about state powe=\nr purchases had been closely guarded until recently. Gov. Gray Davis, press=\nured by lawsuits and a court ruling, released edited versions last week of =\n38 long-term power contracts worth $43 billion.  The Davis administration s=\naid it agreed to release contract information because power prices have dro=\npped, easing competitive pressures.    =09\n\n\n\n\n\nEx-worker: Duke manipulated market =09\n=09\n\n\n\n\nBy Bill Ainsworth  UNION-TRIBUNE STAFF WRITER  June 22, 2001  SACRAMENTO --=\nA former operator at Duke Energy's Chula Vista plant said he was told freq=\nuently by company officials during the past year to alter the plant's outpu=\nt in a way that may have boosted electricity prices.  The operator, Jimmy O=\nlkjer, said he was even ordered to cut power generation during energy emerg=\nencies, when the state faced rolling blackouts because of a scarce supply o=\nf electricity.  He said he believes reducing the electricity generation hel=\nped the company charge higher prices. \"It looks like that's what they were =\ndoing,\" Olkjer said in an interview.  He and another former plant employee =\nsaid that during the past year the company regularly operated its least-eff=\nicient turbine, possibly to justify higher prices.  The allegations, which =\nthey plan to repeat today at a state Senate hearing investigating power gen=\nerators, provide the first insider evidence that Duke Energy may have manip=\nulated output at its South Bay plant to drive up prices.  Duke, based in No=\nrth Carolina, leases the South Bay plant from the San Diego Unified Port Di=\nstrict.  A March report by the Independent System Operator, which manages C=\nalifornia's electricity grid, alleged that by withholding power Duke and fo=\nur other owners of generating plants have contributed to billions of dollar=\ns in overcharges to California consumers.  Tom Williams, spokesman for Duke=\nEnergy North America, said that varying the output of the generating units=\nat the Chula Vista plant had nothing to do with trying to achieve higher p=\nrices.  He said the changes in output helped balance the state's grid by \"d=\nancing in the market\" -- providing flexibility for grid managers by allowin=\ng the plant to add or reduce power quickly.  Williams added that the aging =\nSouth Bay plant produced as many megawatts last year as it did in 1994.  Ol=\nkjer served as a plant operator for 18 years, mostly when the plant was own=\ned by San Diego Gas & Electric Co. After Duke took over the plant, workers =\nwere guaranteed their jobs for two years. In April, when that period ended,=\nDuke laid off Olkjer and other workers. Now he is retired.  During the two=\nyears Duke has managed the plant, Olkjer said, operators frequently got ca=\nlls from officials with Duke Energy Trading and Marketing in Salt Lake City=\ntelling them to adjust their production schedule.  Some employees at the p=\nlant monitored the hourly price of electricity posted by the Independent Sy=\nstem Operator and recognized a correlation, he said.  \"We noticed that a lo=\nt of times when the price was down (our) megawatts would go down,\" he said.=\n\"If the price was up, often the megawatts would go up.\"  Olkjer said he wa=\ns never told why he was being ordered to turn the plant's output up and dow=\nn. When he asked, he said, company officials told him it was none of his bu=\nsiness.  Still, he was puzzled, particularly when he was told to th

In [ ]:
import json
import pandas as pd

good_rows = []

with open("/content/drive/MyDrive/Infosys_Datasets/cleaned_enron_emails.json", errors="ignore") as f:
    for line in f:
        try:
            good_rows.append(json.loads(line))
        except:
            continue   # skip broken rows

df = pd.DataFrame(good_rows)

In [ ]:
df.shape
df.head()
df.columns

RangeIndex(start=0, stop=0, step=1)

In [ ]:
df.shape

(0, 0)

In [ ]:
df.head()

Empty DataFrame
Columns: []
Index: []

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['index']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'index'}, axis=1)
              .sort_values('index', ascending=True))
  xs = counted['index']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_0.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('count()')

In [ ]:
df.size

0